#ifndef _BRAIN_GLOBAL_H
#define _BRAIN_GLOBAL_H

#define LOG_TYPE (0)
#define LOG_LEVEL NONE

#define CALCULATE_AVERAGE false

#define GAMES_BEFORE_RESTART 10000
//225625.0f
#define TOTAL_NUMBER_OF_GAMES 225625

#define BATTLESIM_TIMEOUT 2400
#define BATTLESIM_RESETTIME 1

#include "types.h"

#endif
