#ifndef _BRAIN_GLOBAL_H
#define _BRAIN_GLOBAL_H

#define LOG_TYPE (BATTLESIM, MISC)
#define LOG_LEVEL ALL

#define CALCULATE_AVERAGE false

//10000
#define GAMES_BEFORE_RESTART 2
//225625
#define TOTAL_NUMBER_OF_GAMES 5

#define BATTLESIM_TIMEOUT 2400
#define BATTLESIM_RESETTIME 1

#include "types.h"

#endif
